
import {
  LayoutDashboard,
  Users,
  Briefcase,
  Newspaper,
  MessageSquare,
  Info,
  FileText,
  ShieldCheck,
  Calendar,
  Contact,
  Clock,
  Folder,
  Mail,
  Calculator,
  Beaker,
  Lightbulb,
  Settings,
  LogOut,
  FilePlus2,
  Database,
  Bug,
  Bell,
  HeartPulse,
  BarChart3,
  DatabaseBackup,
  Wand2,
  Landmark,
  Megaphone,
  PackageSearch,
  Users2,
  Contact2,
  HardHat,
  ArrowDownAZ,
  Trash2,
  ListTodo,
  ImageIcon,
  BookText,
  BrainCircuit,
  GitMerge,
  Pencil,
  ListChecks,
  FilePenLine,
  Route,
  Link as LinkIcon,
  FileOutput,
  FileDigit,
  TrendingUp,
  TrendingDown,
  WalletCards,
  UserPlus,
  Banknote,
  Percent,
  FileSignature,
  ListPlus,
  FileInput,
  Activity,
  Wrench,
} from "lucide-react";
import type { LucideIcon } from 'lucide-react';
import { accountingMenuItems } from '@/data/accounting-menu-items';
import hrMenuItems from '@/data/hr-menu-items';

export interface MenuItem {
  href: string;
  label: string;
  icon: LucideIcon;
}


export const allMenuItems: MenuItem[] = [
  { href: "/action-manager", label: "Action Manager", icon: LayoutDashboard },
  { href: "/master-mind", label: "Task & Event Mngr", icon: BrainCircuit },
  { href: "/command-centre", label: "Command Centre", icon: BrainCircuit },
  { href: "/action-manager/manage", label: "Action Manager Settings", icon: LayoutDashboard },
  { href: "/action-manager/trash", label: "Trash", icon: Trash2 },
  { href: "/a-z-sort", label: "A-Z Sort", icon: ArrowDownAZ },
  { href: "/hr-manager", label: "HR Hub", icon: Users2 },
  { href: "/crm/plan", label: "CRM Hub", icon: Users2 },
  { href: "/inventory-manager", label: "Inventory", icon: PackageSearch },
  { href: "/marketing-manager", label: "Marketing", icon: Megaphone },
  { href: "/google", label: "Google Apps", icon: Wand2 },
  { href: "/backup", label: "Backup", icon: DatabaseBackup },
  { href: "/hytexercise", label: "Hytexercise", icon: HeartPulse },
  { href: "/dev-notes", label: "Dev Notes", icon: BookText },
  { href: "/forms", label: "Forms", icon: FilePlus2 },
  { href: "/image-generator", label: "Image Generation", icon: ImageIcon },
  { href: "/user-list", label: "User List", icon: Users2 },
  { href: "/settings", label: "Settings", icon: Settings },
  { href: "/logout", label: "Logout", icon: LogOut },
  { href: "/email-hub", label: "Email Hub", icon: Mail },
  { href: "/contacts", label: "Contacts Hub", icon: Contact },
  { href: "/projects/all", label: "Projects", icon: Briefcase },
  { href: "/to-do", label: "To-Do List", icon: ListChecks },
  { href: "/calendar", label: "Calendar", icon: Calendar },
  { href: "/document-manager", label: "Document Manager", icon: Folder },
  { href: "/idea-board", label: "Idea Board", icon: Lightbulb },
  { href: "/research", label: "Research", icon: Beaker },
  ...accountingMenuItems,
  ...hrMenuItems,
];
