
import {
  LayoutDashboard,
  Users,
  Briefcase,
  Newspaper,
  MessageSquare,
  Info,
  FileText,
  ShieldCheck,
  Calendar,
  Contact,
  Clock,
  Folder,
  Mail,
  Calculator,
  Lightbulb,
  Settings,
  LogOut,
  Database,
  Bug,
  Bell,
  HeartPulse,
  BarChart3,
  Wand2,
  Landmark,
  Megaphone,
  PackageSearch,
  Users2,
  Contact2,
  HardHat,
  ArrowDownAZ,
  Trash2,
  ListTodo,
  BookText,
  BrainCircuit,
  GitMerge,
  Pencil,
  ListChecks,
  FilePenLine,
  Route,
  Link as LinkIcon,
  FileOutput,
  FileDigit,
  TrendingUp,
  TrendingDown,
  BookOpen,
  ClipboardList,
  PlayCircle,
  Wrench,
  DatabaseBackup,
  Globe,
  MessageCircleQuestion,
  Search,
  Image,
} from "lucide-react";
import type { LucideIcon } from 'lucide-react';
import { accountingMenuItems } from '@/data/accounting-menu-items';
import hrMenuItems from '@/data/hr-menu-items';

export interface MenuItem {
  href: string;
  label: string;
  icon: LucideIcon;
}


export const allMenuItems: MenuItem[] = [
  { href: "/action-manager", label: "Action Manager", icon: LayoutDashboard },
  { href: "/website", label: "Website", icon: Globe },
  { href: "/master-mind", label: "Time & Event Scheduler", icon: BrainCircuit },
  { href: "/command-centre", label: "Command Centre", icon: BrainCircuit },
  { href: "/action-manager/manage", label: "Action Manager Settings", icon: LayoutDashboard },
  { href: "/action-manager/trash", label: "Trash", icon: Trash2 },
  { href: "/a-z-sort", label: "A-Z Sort", icon: ArrowDownAZ },
  { href: "/hr-manager", label: "HR Hub", icon: Users2 },
  { href: "/crm/plan", label: "CRM Hub", icon: Users2 },
  { href: "/inventory-manager/track", label: "Inventory", icon: PackageSearch },
  { href: "/marketing-manager", label: "Marketing", icon: Megaphone },
  { href: "/google", label: "Google Apps", icon: Wand2 },
  { href: "/hytexercise", label: "Hytexercise", icon: HeartPulse },
  { href: "/user-list", label: "User List", icon: Users2 },
  { href: "/tools/image-generator", label: "Image Generator", icon: Wand2 },
  { href: "/settings", label: "Settings", icon: Settings },
  { href: "/image-manager", label: "Image Manager", icon: Image },
  { href: "/backup", label: "Backups", icon: DatabaseBackup },
  { href: "/logout", label: "Logout", icon: LogOut },
  { href: "/email-hub", label: "Email Hub", icon: Mail },
  { href: "/contacts", label: "Contacts Hub", icon: Contact },
  { href: "/projects/all", label: "Projects", icon: Briefcase },
  { href: "/to-do", label: "To-Do List", icon: ListChecks },
  { href: "/calendar", label: "Calendar", icon: Calendar },
  { href: "/document-manager", label: "Document Manager", icon: Folder },
  { href: "/idea-board", label: "Idea Board", icon: Lightbulb },
  { href: "/reports/client-statement", label: "Client Statement", icon: FileText },
  { href: "/reports/time-log", label: "Time Log Report", icon: Clock },
  { href: "/reports/search", label: "Advanced Search", icon: Search },
  { href: "/feedback", label: "Feedback", icon: Megaphone },
  { href: "/blog/moderation", label: "Comment Moderation", icon: MessageCircleQuestion },
  ...accountingMenuItems,
  ...hrMenuItems,
];
